version: '3.1'

services:
  codrr_pg:
    image: postgres:14
    container_name: osodreamer
    restart: always
    environment:
      POSTGRES_DB: user_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: juniorpitu
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432

      